# Generated by Django 4.2.15 on 2024-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_coupon_code_alter_coupon_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
