# Generated by Django 4.2.15 on 2024-08-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), (
                'Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
